version: '3.4'

services:
    usermanagementservice.api:
        image: ${DOCKER_REGISTRY-}usermanagementserviceapi
        build:
            context: .
            dockerfile: UserManagementService.Api/Dockerfile
        ports:
            - "5000:5000"
            - "5001:5001"
